# Generated by Django 5.2.7 on 2025-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0020_alter_todo_due_on_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional YouTube video URL to embed with this task', null=True, verbose_name='YouTube Video URL'),
        ),
    ]
